services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://159.223.237.95/
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase?schema=public
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGPASSWORD=password
    depends_on:
      - db

volumes:
  postgres_data:
