services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DATABASE_URL=${DATABASE_URL}
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
      
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
