FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install 

COPY prisma ./prisma/
COPY . .

RUN npx prisma generate

# Add your wait-for script
COPY wait-for-it.sh wait-for-it.sh
RUN chmod +x wait-for-it.sh

# Wait for the database to be ready
CMD ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "build"]

EXPOSE 3000

CMD ["npm", "start"]
