services:
  db:
    image: postgres:latest
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
    networks:
      - default
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase?schema=public
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
