name: Deploy Docker Container

on:
  push:
    branches:
      - prod

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./webapp
          file: ./webapp/Dockerfile
          push: true
          tags: simonsejse/dis-webapp:latest

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            docker pull simonsejse/dis-webapp:latest
            docker stop dis-webapp || true
            docker rm dis-webapp || true
            docker run -t -d -p 80:3000 --name dis-webapp simonsejse/dis-webapp:latest
